export {
  deckAtom,
  activeSlideIndexAtom,
  selectedAtom,
  selectedPathAtom,
  selectedItemsAtom,
  editorOpenAtom,
  presentingAtom,
  exportModeAtom,
  isExportingAtom,
  editingTextIndexAtom,
  editingTextPathAtom,
  editingBulletsIndexAtom,
  editingBulletsPathAtom,
  editingBulletsDraftAtom,
  editingTableIndexAtom,
  editingTablePathAtom,
  editingTableDraftAtom,
  editingChartIndexAtom,
  editingChartPathAtom,
  editingChartDraftAtom,
  editingSvgIndexAtom,
  editingSvgPathAtom,
  editingSvgDraftAtom,
  selectedTableCellAtom,
  activeSlideAtom,
  selectedIndexAtom,
  selectedElementAtom,
  selectedResolvedElementAtom,
  selectedTextElementAtom,
  selectedBulletsElementAtom,
  selectedImageElementAtom,
  selectedShapeElementAtom,
  selectedTableElementAtom,
  selectedChartElementAtom,
  editingTextElementAtom,
  editingBulletsElementAtom,
  editingTableElementAtom,
  editingChartElementAtom,
  editingSvgElementAtom,
  activeSlideOverflowIndicesAtom,
  selectedElementOverflowsAtom,
  type ExportMode,
  type TextSlideElement,
  type BulletsSlideElement,
  type ImageSlideElement,
  type ShapeSlideElement,
  type TableSlideElement,
  type ChartSlideElement,
  type SvgSlideElement,
  type TableCellSelection,
} from "./atoms";
export {
  selectElementAtom,
  selectElementsAtom,
  setSelectionAtom,
  updateDeckTitleAtom,
  updateDeckThemeColorAtom,
  applyDeckThemePresetAtom,
  updateActiveSlideAtom,
  updateElementAtom,
  updateElementAtPathAtom,
  updateElementsAtom,
  patchSelectedAtom,
  addElementAtom,
  insertSlideAtom,
  moveSlideAtom,
  insertElementAtom,
  insertElementsAtom,
  duplicateSelectedAtom,
  deleteSelectedComponentRunAtom,
  deleteSelectedAtom,
} from "./actions";
export { getComponentRun, type ComponentRun } from "./componentGroups";
export { createDefaultElement } from "./createDefaultElement";
export { undoAtom, redoAtom, canUndoAtom, canRedoAtom } from "./history";
